# Shell variables
# Generated by 'wal'
wallpaper='/home/davidh/.config/awesome/wp/default.jpg'

# Special
background='#00001B'
foreground='#d197e2'
cursor='#d197e2'

# Colors
color0='#00001B'
color1='#64049F'
color2='#7A4DBB'
color3='#5E22CF'
color4='#544EE6'
color5='#9C05A3'
color6='#DC0FA5'
color7='#d197e2'
color8='#92699e'
color9='#64049F'
color10='#7A4DBB'
color11='#5E22CF'
color12='#544EE6'
color13='#9C05A3'
color14='#DC0FA5'
color15='#d197e2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
